//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACCOUNT()
        {
            this.DELIVERY_REQUESTS = new HashSet<DELIVERY_REQUESTS>();
            this.GOODS_DELIVERY_NOTE = new HashSet<GOODS_DELIVERY_NOTE>();
            this.GOODS_RECEIVED_NOTE = new HashSet<GOODS_RECEIVED_NOTE>();
            this.ORDERS = new HashSet<ORDER>();
        }
    
        public int ID { get; set; }
        public int Staff_ID { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string DisplayName { get; set; }
        public int Role_ID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ROLE ROLE { get; set; }
        public virtual STAFF STAFF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_REQUESTS> DELIVERY_REQUESTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_DELIVERY_NOTE> GOODS_DELIVERY_NOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_RECEIVED_NOTE> GOODS_RECEIVED_NOTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERS { get; set; }
    }
}
