//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_REQUEST_DETAILS
    {
        public int Product_ID { get; set; }
        public int Request_ID { get; set; }
        public int Quantity { get; set; }
    
        public virtual DELIVERY_REQUESTS DELIVERY_REQUESTS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
