//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY_REQUESTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DELIVERY_REQUESTS()
        {
            this.DELIVERY_REQUEST_DETAILS = new HashSet<DELIVERY_REQUEST_DETAILS>();
            this.GOODS_DELIVERY_NOTE = new HashSet<GOODS_DELIVERY_NOTE>();
        }
    
        public int ID { get; set; }
        public int Account_ID { get; set; }
        public int Store_ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string MoreInfo { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_REQUEST_DETAILS> DELIVERY_REQUEST_DETAILS { get; set; }
        public virtual STORE STORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_DELIVERY_NOTE> GOODS_DELIVERY_NOTE { get; set; }
    }
}
