//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOODS_RECEIVED_NOTE_DETAILS
    {
        public int Product_ID { get; set; }
        public int GRN_ID { get; set; }
        public int Supplier_id { get; set; }
        public Nullable<int> Quantity_of_request { get; set; }
        public Nullable<int> Actual_Amount { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual GOODS_RECEIVED_NOTE GOODS_RECEIVED_NOTE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
