//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.DELIVERY_REQUEST_DETAILS = new HashSet<DELIVERY_REQUEST_DETAILS>();
            this.GOODS_DELIVERY_NOTE_DETAILS = new HashSet<GOODS_DELIVERY_NOTE_DETAILS>();
            this.GOODS_RECEIVED_NOTE_DETAILS = new HashSet<GOODS_RECEIVED_NOTE_DETAILS>();
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
            this.PRODUCT_STORE = new HashSet<PRODUCT_STORE>();
            this.PRODUCT_WAREHOUSE = new HashSet<PRODUCT_WAREHOUSE>();
            this.SHIPMENT_OF_GOODS = new HashSet<SHIPMENT_OF_GOODS>();
            this.SUPPLIERS = new HashSet<SUPPLIER>();
            this.TYPE_OF_CATEGORY = new HashSet<TYPE_OF_CATEGORY>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public Nullable<int> Color_ID { get; set; }
        public Nullable<int> Brand_ID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string UserManual { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        public virtual COLOR COLOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY_REQUEST_DETAILS> DELIVERY_REQUEST_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_DELIVERY_NOTE_DETAILS> GOODS_DELIVERY_NOTE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOODS_RECEIVED_NOTE_DETAILS> GOODS_RECEIVED_NOTE_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_STORE> PRODUCT_STORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_WAREHOUSE> PRODUCT_WAREHOUSE { get; set; }
        public virtual UNIT UNIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHIPMENT_OF_GOODS> SHIPMENT_OF_GOODS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUPPLIER> SUPPLIERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPE_OF_CATEGORY> TYPE_OF_CATEGORY { get; set; }
    }
}
