//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWarehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHIPMENT_OF_GOODS
    {
        public int ID { get; set; }
        public int GRN_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> EXP { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual GOODS_RECEIVED_NOTE GOODS_RECEIVED_NOTE { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
